package com.capgemini.OFDApp.domain;
import java.io.Serializable;
import javax.persistence.*;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotEmpty;

import com.fasterxml.jackson.annotation.JsonIgnore;
/**
 * This customer Class is a domain, which represents data and it will be moving
 * layer to layer.
 * 
 * @author Subhasree
 *
 */
@Entity
@Table(name="customer_master")
public class Customer implements Serializable {
	@Id
	@Column(name="customerid")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	/*
	 * id of the customer is autogenerated
	 */
	private int customerId;
	/*
	 * first name of customer
	 */
	@Column
	private String firstName;
	/*
	 * last name of customer
	 */
	@Column
	private String lastName;
	@Column
	/*
	 * gender of customer
	 */
	private String gender;
	@Column
	/*
	 * email of customer
	 */
	private String email;
	@Column
	/*
	 * mobile number of customer
	 */
	private String mobileNumber;
	@Column
	/*
	 * age of the customer
	 */
	private int age; 
	/*
	 * one to one relationship with address
	 */
	@OneToOne(mappedBy="customer",cascade=CascadeType.ALL, fetch = FetchType.EAGER)
//	@OneToOne
	@JoinColumn(name="address_id")
	private Address address;
	/*
	 * one to one relationship with food cart
	 */
	
	@OneToOne(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
	@JoinColumn(name="cartid")
	private FoodCart foodcart;
	/*
	 * setters of getters
	 */
	public int getCustomerId() {
		return customerId;
	}
	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}
	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	public String getLastName() {
		return lastName;
	}
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	public String getGender() {
		return gender;
	}
	public void setGender(String gender) {
		this.gender = gender;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getMobileNumber() {
		return mobileNumber;
	}
	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}
	public int getAge() {
		return age;
	}
	public void setAge(int age) {
		this.age = age;
	}
	@JsonIgnore
	public FoodCart getFoodcart() {
		return foodcart;
	}
	public void setFoodcart(FoodCart foodcart) {
		this.foodcart = foodcart;
	}
	//@JsonIgnore
	public Address getAddress() {
		return address;
	}
	public void setAddress(Address address) {
		this.address = address;
	}


}
